baseURL = "https://rouxles.github.io/anto-ib-english"
languageCode = "en-us"
title = "IB English - Antonio Kam"
theme = "beautifulhugo"
publishDir = "docs"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3


